In [ ]:
import numpy as np
from sklearn import svm
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
import pickle

from google.colab import drive
%matplotlib inline

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
pkl_filename = "/svm_cyh.pkl"
DATA_PATH = "/content/drive/Shareddrives/MachineLearning"

infile = open(DATA_PATH + pkl_filename,'rb')
model = pickle.load(infile)

In [ ]:
model

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
X_train = np.load('/content/drive/Shareddrives/MachineLearning/project_dataset/X_train.npy')
X_valid = np.load('/content/drive/Shareddrives/MachineLearning/project_dataset/X_valid.npy')
X_test = np.load('/content/drive/Shareddrives/MachineLearning/project_dataset/X_test.npy')
y_train = np.load('/content/drive/Shareddrives/MachineLearning/project_dataset/y_train.npy')
y_valid = np.load('/content/drive/Shareddrives/MachineLearning/project_dataset/y_valid.npy')
y_test = np.load('/content/drive/Shareddrives/MachineLearning/project_dataset/y_test.npy')

In [ ]:
X_train, y_train = shuffle(X_train, y_train, random_state=0)
X_valid, y_valid= shuffle(X_valid, y_valid, random_state=0)
X_test, y_test = shuffle(X_test, y_test, random_state=0)

In [ ]:
print(X_test.shape)
print(y_test.shape)

(16100, 90, 90)
(16100,)


In [ ]:
X_train = X_train / 255
X_valid = X_valid / 255
X_test = X_test / 255
X_train = X_train[...,np.newaxis]
X_valid = X_valid[...,np.newaxis]
X_test = X_test[...,np.newaxis]

In [ ]:
print(X_test.shape)
print(y_test.shape)

(16100, 90, 90, 1)
(16100,)


In [ ]:
M = X_train.shape[0]
X_train = X_train.reshape(M,-1)
print(X_train.shape)
print(y_train.shape)

(48300, 8100)
(48300,)


In [ ]:
M = X_test.shape[0]
X_test = X_test.reshape(M,-1)
print(X_test.shape)
print(y_test.shape)

(16100, 8100)
(16100,)


In [ ]:
train_score = model.score(X_train,y_train)

In [ ]:
ypred_sklearn = model.predict(X_test)
test_score = model.score(X_test,y_test)

0.834472049689441

In [ ]:
from sklearn.metrics import confusion_matrix

cnf_matrix_sklearn = confusion_matrix(y_test, ypred_sklearn)
print(cnf_matrix_sklearn)

[[94  0  0 ...  0  0  0]
 [ 0 99  0 ...  0  0  0]
 [ 0  0 98 ...  0  0  0]
 ...
 [ 1  0  1 ... 59  0  0]
 [ 0  0  0 ...  3 60  0]
 [ 0  0  0 ...  0  2 37]]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, ypred_sklearn))

              precision    recall  f1-score   support

           0       0.80      0.94      0.87       100
           1       0.95      0.99      0.97       100
           2       0.88      0.98      0.93       100
           3       0.92      1.00      0.96       100
           4       0.96      1.00      0.98       100
           5       0.91      0.96      0.94       100
           6       0.94      0.90      0.92       100
           7       0.82      0.95      0.88       100
           8       0.80      0.86      0.83       100
           9       0.73      0.73      0.73       100
          10       0.74      0.93      0.83       100
          11       0.87      0.91      0.89       100
          12       0.78      0.76      0.77       100
          13       0.75      0.88      0.81       100
          14       0.92      1.00      0.96       100
          15       0.83      0.86      0.84       100
          16       0.80      0.91      0.85       100
          17       0.79    